/** Map process / exe / bundle names to friendly app labels. */
const APP_LABELS: Record<string, string> = {
  "cursor.exe": "Cursor",
  cursor: "Cursor",
  "cursor.app": "Cursor",
  "code.exe": "VS Code",
  code: "VS Code",
  "code.app": "VS Code",
  "code - insiders.exe": "VS Code",
  "visual studio code.app": "VS Code",
  "windsurf.exe": "Windsurf",
  "windsurf.app": "Windsurf",
  "zed.exe": "Zed",
  "zed.app": "Zed",
  zed: "Zed",
  "slack.exe": "Slack",
  slack: "Slack",
  "slack.app": "Slack",
  "discord.exe": "Discord",
  discord: "Discord",
  "discord.app": "Discord",
  "outlook.exe": "Outlook",
  "olk.exe": "Outlook",
  "microsoft outlook.app": "Outlook",
  "winword.exe": "Word",
  "microsoft word.app": "Word",
  "excel.exe": "Excel",
  "microsoft excel.app": "Excel",
  "powerpnt.exe": "PowerPoint",
  "microsoft powerpoint.app": "PowerPoint",
  "onenote.exe": "OneNote",
  "microsoft onenote.app": "OneNote",
  "notion.exe": "Notion",
  notion: "Notion",
  "notion.app": "Notion",
  "obsidian.exe": "Obsidian",
  obsidian: "Obsidian",
  "obsidian.app": "Obsidian",
  "logseq.exe": "Logseq",
  "logseq.app": "Logseq",
  logseq: "Logseq",
  "chrome.exe": "Chrome",
  chrome: "Chrome",
  "google-chrome": "Chrome",
  "google chrome.app": "Chrome",
  chromium: "Chrome",
  "chromium.exe": "Chrome",
  "msedge.exe": "Edge",
  "microsoft-edge": "Edge",
  "microsoft edge.app": "Edge",
  "firefox.exe": "Firefox",
  firefox: "Firefox",
  "firefox.app": "Firefox",
  "brave.exe": "Brave",
  brave: "Brave",
  "brave-browser": "Brave",
  "brave browser.app": "Brave",
  "opera.exe": "Opera",
  opera: "Opera",
  "opera.app": "Opera",
  "vivaldi.exe": "Vivaldi",
  "arc.exe": "Arc",
  "arc.app": "Arc",
  "safari.app": "Safari",
  "spotify.exe": "Spotify",
  spotify: "Spotify",
  "spotify.app": "Spotify",
  "teams.exe": "Teams",
  "ms-teams.exe": "Teams",
  teams: "Teams",
  "microsoft teams.app": "Teams",
  "notepad.exe": "Notepad",
  "notepad++.exe": "Notepad++",
  gedit: "Text Editor",
  kate: "Kate",
  mousepad: "Text Editor",
  "textedit.app": "TextEdit",
  "windowsterminal.exe": "Terminal",
  "powershell.exe": "PowerShell",
  "pwsh.exe": "PowerShell",
  "cmd.exe": "Command Prompt",
  "explorer.exe": "File Explorer",
  "finder.app": "Finder",
  "gnome-terminal": "Terminal",
  konsole: "Terminal",
  alacritty: "Alacritty",
  kitty: "Kitty",
  wezterm: "WezTerm",
  "terminal.app": "Terminal",
  "iterm2.app": "iTerm",
  "warp.app": "Warp",
  "figma.exe": "Figma",
  figma: "Figma",
  "figma.app": "Figma",
  "telegram.exe": "Telegram",
  telegram: "Telegram",
  "telegram-desktop": "Telegram",
  "telegram.app": "Telegram",
  "whatsapp.exe": "WhatsApp",
  whatsapp: "WhatsApp",
  "whatsapp.app": "WhatsApp",
  "signal.exe": "Signal",
  "signal.app": "Signal",
  "signal-desktop": "Signal",
  "messages.app": "Messages",
  "mail.app": "Mail",
  "notes.app": "Notes",
  "zoom.exe": "Zoom",
  zoom: "Zoom",
  "zoom.us.app": "Zoom",
  "thunderbird.exe": "Thunderbird",
  "thunderbird.app": "Thunderbird",
  thunderbird: "Thunderbird",
  "mailspring.exe": "Mailspring",
  "mailspring.app": "Mailspring",
  mailspring: "Mailspring",
  "postman.exe": "Postman",
  "postman.app": "Postman",
  postman: "Postman",
  "devenv.exe": "Visual Studio",
  "idea64.exe": "IntelliJ IDEA",
  "intellij idea.app": "IntelliJ IDEA",
  "pycharm64.exe": "PyCharm",
  "pycharm.app": "PyCharm",
  "webstorm64.exe": "WebStorm",
  "webstorm.app": "WebStorm",
  "android studio.exe": "Android Studio",
  "android studio.app": "Android Studio",
  "xcode.app": "Xcode",
  "github desktop.exe": "GitHub Desktop",
  "github desktop.app": "GitHub Desktop",
  "docker desktop.exe": "Docker",
  "docker.app": "Docker",
  "todoist.exe": "Todoist",
  "todoist.app": "Todoist",
  "asana.exe": "Asana",
  "asana.app": "Asana",
  "trello.exe": "Trello",
  "trello.app": "Trello",
  "linear.exe": "Linear",
  "linear.app": "Linear",
  "canva.exe": "Canva",
  "canva.app": "Canva",
  "miro.exe": "Miro",
  "miro.app": "Miro",
  "1password.exe": "1Password",
  "1password.app": "1Password",
  "1password": "1Password",
  "bitwarden.exe": "Bitwarden",
  "bitwarden.app": "Bitwarden",
  "grammarly.exe": "Grammarly",
  "grammarly.app": "Grammarly",
  "scrivener.exe": "Scrivener",
  "scrivener.app": "Scrivener",
  "typora.exe": "Typora",
  "typora.app": "Typora",
  typora: "Typora",
  "joplin.exe": "Joplin",
  "joplin.app": "Joplin",
  joplin: "Joplin",
  "steam.exe": "Steam",
  "twitch.exe": "Twitch",
  "twitch.app": "Twitch",
  "obs64.exe": "OBS",
  "obs.exe": "OBS",
  "obs.app": "OBS",
  "acrobat.exe": "Acrobat",
  "adobe acrobat.app": "Acrobat",
  "photoshop.exe": "Photoshop",
  "illustrator.exe": "Illustrator",
  "blender.exe": "Blender",
  blender: "Blender",
  "blender.app": "Blender",
  "pages.app": "Pages",
  "numbers.app": "Numbers",
  "keynote.app": "Keynote",
  "calendar.app": "Calendar",
  "reminders.app": "Reminders",
  "things3.app": "Things",
  "fantastical.app": "Fantastical",
  "raycast.app": "Raycast",
  "alfred.app": "Alfred",
  unknown: "Unknown",
};

export function friendlyAppName(raw: string): string {
  if (!raw) return "Unknown";
  const lower = raw.toLowerCase().trim();
  if (APP_LABELS[lower]) return APP_LABELS[lower];

  // Strip path if present
  const base = lower.includes("\\")
    ? lower.split("\\").pop() || lower
    : lower.includes("/")
      ? lower.split("/").pop() || lower
      : lower;

  if (APP_LABELS[base]) return APP_LABELS[base];

  let name = base
    .replace(/\.exe$/i, "")
    .replace(/\.app$/i, "")
    .replace(/[-_]+/g, " ");
  return name
    .split(" ")
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}
