//! Intelligent per-app tone presets.
//!
//! Matching uses case-insensitive substrings on exe + optional window title.
//! Title-specific rules (e.g. Chrome + "Gmail") beat bare-exe rules via
//! specificity sorting in `get_tone_for_app`.

/// (exe_pattern, title_pattern, tone)
pub type ProfileSeed = (&'static str, &'static str, &'static str);

const BROWSERS: &[&str] = &[
    "chrome.exe",
    "msedge.exe",
    "firefox.exe",
    "brave.exe",
    "opera.exe",
    "vivaldi.exe",
    "arc.exe",
    "chromium.exe",
    "google chrome.app",
    "microsoft edge.app",
    "firefox.app",
    "brave browser.app",
    "safari.app",
    "opera.app",
    "arc.app",
    "google-chrome",
    "chromium",
    "microsoft-edge",
    "brave-browser",
    "firefox",
    "opera",
];

/// Web destinations keyed by a substring of the browser tab/window title.
const WEB_TONES: &[(&str, &str)] = &[
    // Email / workmail — formal
    ("Gmail", "formal"),
    ("Mail -", "formal"),
    ("Outlook", "formal"),
    ("Outlook.com", "formal"),
    ("Yahoo Mail", "formal"),
    ("Proton Mail", "formal"),
    ("ProtonMail", "formal"),
    ("Fastmail", "formal"),
    ("Zoho Mail", "formal"),
    ("iCloud Mail", "formal"),
    ("AOL Mail", "formal"),
    ("Hey.com", "formal"),
    ("Superhuman", "formal"),
    ("Front |", "formal"),
    ("Missive", "formal"),
    ("Spark Mail", "formal"),
    // Professional / CRM / support — formal
    ("LinkedIn", "formal"),
    ("Salesforce", "formal"),
    ("HubSpot", "formal"),
    ("Zendesk", "formal"),
    ("Intercom", "formal"),
    ("Freshdesk", "formal"),
    ("Freshsales", "formal"),
    ("Pipedrive", "formal"),
    ("Close.com", "formal"),
    ("Copper CRM", "formal"),
    ("Zoho CRM", "formal"),
    ("Monday.com", "formal"),
    ("Asana", "formal"),
    ("ClickUp", "formal"),
    ("Jira", "formal"),
    ("Confluence", "formal"),
    ("Linear", "formal"),
    ("Shortcut", "formal"),
    ("Basecamp", "formal"),
    ("Smartsheet", "formal"),
    ("Wrike", "formal"),
    ("Airtable", "formal"),
    ("Notion", "prose"),
    ("Coda.io", "prose"),
    ("Coda ", "prose"),
    ("Google Docs", "prose"),
    ("Google Sheets", "default"),
    ("Google Slides", "formal"),
    ("Docs -", "prose"),
    ("Sheets -", "default"),
    ("Slides -", "formal"),
    ("Dropbox Paper", "prose"),
    ("Quip", "prose"),
    ("Craft.do", "prose"),
    ("Bear ", "prose"),
    ("Grammarly", "prose"),
    ("Hemingway", "prose"),
    ("Word Online", "prose"),
    ("Word for the web", "prose"),
    ("Excel Online", "default"),
    ("PowerPoint Online", "formal"),
    ("OneNote", "prose"),
    ("Evernote", "prose"),
    ("Roam Research", "prose"),
    ("RemNote", "prose"),
    ("Logseq", "prose"),
    ("Reflect.app", "prose"),
    ("Mem.ai", "prose"),
    ("Obsidian Publish", "prose"),
    // Chat / social — casual
    ("Discord", "casual"),
    ("Slack", "casual"),
    ("WhatsApp", "casual"),
    ("Telegram", "casual"),
    ("Messenger", "casual"),
    ("Facebook", "casual"),
    ("Instagram", "casual"),
    ("TikTok", "casual"),
    ("Twitter", "casual"),
    (" / X", "casual"),
    ("X (", "casual"),
    ("x.com", "casual"),
    ("Reddit", "casual"),
    ("Twitch", "casual"),
    ("Snapchat", "casual"),
    ("Threads", "casual"),
    ("Mastodon", "casual"),
    ("Bluesky", "casual"),
    ("BeReal", "casual"),
    ("GroupMe", "casual"),
    ("Signal", "casual"),
    ("iMessage", "casual"),
    ("Messages for web", "casual"),
    ("Google Chat", "casual"),
    ("Google Hangouts", "casual"),
    ("Hangouts", "casual"),
    ("ChatGPT", "default"),
    ("Claude", "default"),
    ("Perplexity", "default"),
    ("Gemini", "default"),
    ("Copilot", "default"),
    ("Character.AI", "casual"),
    // Dev / code web — code
    ("GitHub", "code"),
    ("GitLab", "code"),
    ("Bitbucket", "code"),
    ("Stack Overflow", "code"),
    ("Stack Exchange", "code"),
    ("CodePen", "code"),
    ("CodeSandbox", "code"),
    ("StackBlitz", "code"),
    ("Replit", "code"),
    ("JSFiddle", "code"),
    ("Glitch", "code"),
    ("Vercel", "code"),
    ("Netlify", "code"),
    ("Railway", "code"),
    ("Render", "code"),
    ("Fly.io", "code"),
    ("DigitalOcean", "code"),
    ("AWS ", "code"),
    ("Amazon Web Services", "code"),
    ("Azure", "code"),
    ("Google Cloud", "code"),
    ("Cloudflare", "code"),
    ("Console Home", "code"),
    ("npm ", "code"),
    ("crates.io", "code"),
    ("PyPI", "code"),
    ("Docker Hub", "code"),
    ("Kubernetes", "code"),
    ("Datadog", "code"),
    ("Sentry", "code"),
    ("Grafana", "code"),
    ("New Relic", "code"),
    ("PagerDuty", "formal"),
    ("Statuspage", "formal"),
    // Design — default/prose
    ("Figma", "default"),
    ("FigJam", "casual"),
    ("Canva", "default"),
    ("Miro", "casual"),
    ("Mural", "casual"),
    ("Whimsical", "casual"),
    ("Lucidchart", "formal"),
    ("Excalidraw", "casual"),
    ("Adobe Express", "default"),
    ("Photopea", "default"),
    // Meetings / calendar — formal-ish
    ("Google Meet", "formal"),
    ("Zoom Meeting", "formal"),
    ("Zoom Webinar", "formal"),
    ("Calendly", "formal"),
    ("Calendar", "formal"),
    ("Google Calendar", "formal"),
    ("When2meet", "casual"),
    ("Doodle", "casual"),
    // Commerce / finance — formal
    ("Stripe", "formal"),
    ("PayPal", "formal"),
    ("Square Dashboard", "formal"),
    ("Shopify", "formal"),
    ("QuickBooks", "formal"),
    ("Xero", "formal"),
    ("Wave Accounting", "formal"),
    ("FreshBooks", "formal"),
    ("Expensify", "formal"),
    ("Ramp ", "formal"),
    ("Brex", "formal"),
    ("Mercury", "formal"),
    ("Wise ", "formal"),
    ("Bank of America", "formal"),
    ("Chase ", "formal"),
    ("Wells Fargo", "formal"),
    ("American Express", "formal"),
    ("Coinbase", "formal"),
    ("Robinhood", "casual"),
    ("E*TRADE", "formal"),
    ("Fidelity", "formal"),
    ("Vanguard", "formal"),
    // Support / docs / knowledge — formal/prose
    ("Help Center", "formal"),
    ("Helpdesk", "formal"),
    ("ServiceNow", "formal"),
    ("Wikipedia", "prose"),
    ("Medium", "prose"),
    ("Substack", "prose"),
    ("Ghost", "prose"),
    ("WordPress", "prose"),
    ("Webflow", "default"),
    ("Framer", "default"),
    ("Carrd", "default"),
    // Education
    ("Coursera", "prose"),
    ("Udemy", "casual"),
    ("Khan Academy", "prose"),
    ("Canvas", "formal"),
    ("Blackboard", "formal"),
    ("Google Classroom", "formal"),
    // Misc productivity
    ("Trello", "casual"),
    ("Todoist", "casual"),
    ("TickTick", "casual"),
    ("Things ", "casual"),
    ("Any.do", "casual"),
    ("Remember The Milk", "casual"),
    ("Pocket", "casual"),
    ("Raindrop", "casual"),
    ("Feedly", "casual"),
    ("YouTube", "casual"),
    ("Netflix", "casual"),
    ("Spotify", "casual"),
    ("Apple Music", "casual"),
    ("Amazon Music", "casual"),
    ("Hulu", "casual"),
    ("Disney+", "casual"),
    ("Prime Video", "casual"),
];

/// Native desktop apps: Windows .exe, macOS .app, and common Linux binaries.
const NATIVE: &[ProfileSeed] = &[
    // —— Chat / social (casual) ——
    ("discord.exe", "", "casual"),
    ("discord.app", "", "casual"),
    ("discord", "", "casual"),
    ("slack.exe", "", "casual"),
    ("slack.app", "", "casual"),
    ("slack", "", "casual"),
    ("telegram.exe", "", "casual"),
    ("telegram.app", "", "casual"),
    ("telegram-desktop", "", "casual"),
    ("telegram", "", "casual"),
    ("whatsapp.exe", "", "casual"),
    ("whatsapp.app", "", "casual"),
    ("whatsapp", "", "casual"),
    ("signal.exe", "", "casual"),
    ("signal.app", "", "casual"),
    ("signal-desktop", "", "casual"),
    ("messages.app", "", "casual"),
    ("messenger.exe", "", "casual"),
    ("caprine.exe", "", "casual"),
    ("caprine", "", "casual"),
    ("element.exe", "", "casual"),
    ("element.app", "", "casual"),
    ("element", "", "casual"),
    ("riot.exe", "", "casual"),
    ("skype.exe", "", "casual"),
    ("skype.app", "", "casual"),
    ("skypeforlinux", "", "casual"),
    ("viber.exe", "", "casual"),
    ("viber.app", "", "casual"),
    ("wechat.exe", "", "casual"),
    ("wechat.app", "", "casual"),
    ("line.exe", "", "casual"),
    ("line.app", "", "casual"),
    ("kakaotalk.exe", "", "casual"),
    ("kakaotalk.app", "", "casual"),
    ("teams.exe", "", "casual"),
    ("ms-teams.exe", "", "casual"),
    ("microsoft teams.app", "", "casual"),
    ("teams", "", "casual"),
    ("zoom.exe", "", "casual"),
    ("zoom.us.app", "", "casual"),
    ("zoom", "", "casual"),
    ("webex.exe", "", "formal"),
    ("webex.app", "", "formal"),
    ("cisco webex meetings.app", "", "formal"),
    ("gotomeeting.exe", "", "formal"),
    ("bluejeans.exe", "", "casual"),
    ("ringcentral.exe", "", "formal"),
    ("around.exe", "", "casual"),
    ("loom.exe", "", "casual"),
    ("loom.app", "", "casual"),
    ("steam.exe", "", "casual"),
    ("steam.app", "", "casual"),
    ("steamwebhelper.exe", "", "casual"),
    ("epicgameslauncher.exe", "", "casual"),
    ("battle.net.exe", "", "casual"),
    ("origin.exe", "", "casual"),
    ("twitch.exe", "", "casual"),
    ("twitch.app", "", "casual"),
    ("spotify.exe", "", "casual"),
    ("spotify.app", "", "casual"),
    ("spotify", "", "casual"),
    // —— Email / office (formal / prose) ——
    ("outlook.exe", "", "formal"),
    ("olk.exe", "", "formal"),
    ("microsoft outlook.app", "", "formal"),
    ("mail.app", "", "formal"),
    ("mailspring.exe", "", "formal"),
    ("mailspring.app", "", "formal"),
    ("mailspring", "", "formal"),
    ("thunderbird.exe", "", "formal"),
    ("thunderbird.app", "", "formal"),
    ("thunderbird", "", "formal"),
    ("spark.exe", "", "formal"),
    ("spark mail.app", "", "formal"),
    ("airmail.app", "", "formal"),
    ("postbox.exe", "", "formal"),
    ("emclient.exe", "", "formal"),
    ("winword.exe", "", "prose"),
    ("microsoft word.app", "", "prose"),
    ("word", "", "prose"),
    ("excel.exe", "", "default"),
    ("microsoft excel.app", "", "default"),
    ("powerpnt.exe", "", "formal"),
    ("microsoft powerpoint.app", "", "formal"),
    ("onenote.exe", "", "prose"),
    ("microsoft onenote.app", "", "prose"),
    ("mspub.exe", "", "prose"),
    ("msaccess.exe", "", "formal"),
    ("lync.exe", "", "casual"),
    ("pages.app", "", "prose"),
    ("numbers.app", "", "default"),
    ("keynote.app", "", "formal"),
    ("libreoffice", "", "prose"),
    ("soffice.bin", "", "prose"),
    ("writer", "", "prose"),
    ("calc", "", "default"),
    ("impress", "", "formal"),
    ("abiword", "", "prose"),
    ("gnumeric", "", "default"),
    // —— Notes / knowledge (prose) ——
    ("notion.exe", "", "prose"),
    ("notion.app", "", "prose"),
    ("notion", "", "prose"),
    ("obsidian.exe", "", "prose"),
    ("obsidian.app", "", "prose"),
    ("obsidian", "", "prose"),
    ("logseq.exe", "", "prose"),
    ("logseq.app", "", "prose"),
    ("logseq", "", "prose"),
    ("roam-research.exe", "", "prose"),
    ("bear.app", "", "prose"),
    ("ulysses.app", "", "prose"),
    ("ia writer.app", "", "prose"),
    ("iA Writer.app", "", "prose"),
    ("typora.exe", "", "prose"),
    ("typora.app", "", "prose"),
    ("typora", "", "prose"),
    ("marktext.exe", "", "prose"),
    ("marktext.app", "", "prose"),
    ("zettlr.exe", "", "prose"),
    ("zettlr.app", "", "prose"),
    ("joplin.exe", "", "prose"),
    ("joplin.app", "", "prose"),
    ("joplin", "", "prose"),
    ("standard notes.app", "", "prose"),
    ("standardnotes.exe", "", "prose"),
    ("simplenote.exe", "", "prose"),
    ("simplenote.app", "", "prose"),
    ("notes.app", "", "prose"),
    ("stickies.app", "", "casual"),
    ("evernote.exe", "", "prose"),
    ("evernote.app", "", "prose"),
    ("onenote for windows 10.exe", "", "prose"),
    ("craft.app", "", "prose"),
    ("craft docs.app", "", "prose"),
    ("coda.app", "", "prose"),
    ("scrivenener.app", "", "prose"),
    ("scrivener.exe", "", "prose"),
    ("scrivener.app", "", "prose"),
    ("final draft.exe", "", "prose"),
    ("final draft.app", "", "prose"),
    ("wordpad.exe", "", "prose"),
    ("notepad.exe", "", "default"),
    ("notepad++.exe", "", "code"),
    ("textedit.app", "", "prose"),
    ("gedit", "", "default"),
    ("kate", "", "code"),
    ("mousepad", "", "default"),
    ("leafpad", "", "default"),
    ("pluma", "", "default"),
    // —— Code / IDEs (code) ——
    ("code.exe", "", "code"),
    ("code - insiders.exe", "", "code"),
    ("code.app", "", "code"),
    ("visual studio code.app", "", "code"),
    ("code", "", "code"),
    ("cursor.exe", "", "code"),
    ("cursor.app", "", "code"),
    ("cursor", "", "code"),
    ("windsurf.exe", "", "code"),
    ("windsurf.app", "", "code"),
    ("zed.exe", "", "code"),
    ("zed.app", "", "code"),
    ("zed", "", "code"),
    ("sublime_text.exe", "", "code"),
    ("sublime text.app", "", "code"),
    ("subl", "", "code"),
    ("atom.exe", "", "code"),
    ("atom.app", "", "code"),
    ("brackets.exe", "", "code"),
    ("devenv.exe", "", "code"),
    ("visual studio.app", "", "code"),
    ("rider64.exe", "", "code"),
    ("rider.app", "", "code"),
    ("idea64.exe", "", "code"),
    ("intellij idea.app", "", "code"),
    ("pycharm64.exe", "", "code"),
    ("pycharm.app", "", "code"),
    ("webstorm64.exe", "", "code"),
    ("webstorm.app", "", "code"),
    ("phpstorm64.exe", "", "code"),
    ("phpstorm.app", "", "code"),
    ("clion64.exe", "", "code"),
    ("clion.app", "", "code"),
    ("goland64.exe", "", "code"),
    ("goland.app", "", "code"),
    ("rubymine64.exe", "", "code"),
    ("rubymine.app", "", "code"),
    ("datagrip64.exe", "", "code"),
    ("datagrip.app", "", "code"),
    ("android studio.exe", "", "code"),
    ("android studio.app", "", "code"),
    ("studio64.exe", "", "code"),
    ("xcode.app", "", "code"),
    ("eclipse.exe", "", "code"),
    ("eclipse", "", "code"),
    ("netbeans64.exe", "", "code"),
    ("netbeans", "", "code"),
    ("qtcreator.exe", "", "code"),
    ("qt creator.app", "", "code"),
    ("unity.exe", "", "code"),
    ("unity hub.exe", "", "code"),
    ("unity.app", "", "code"),
    ("unrealeditor.exe", "", "code"),
    ("godot.exe", "", "code"),
    ("godot.app", "", "code"),
    ("blender.exe", "", "default"),
    ("blender.app", "", "default"),
    ("blender", "", "default"),
    ("github desktop.exe", "", "code"),
    ("github desktop.app", "", "code"),
    ("githubdesktop.exe", "", "code"),
    ("sourcetree.exe", "", "code"),
    ("sourcetree.app", "", "code"),
    ("gitkraken.exe", "", "code"),
    ("gitkraken.app", "", "code"),
    ("fork.exe", "", "code"),
    ("fork.app", "", "code"),
    ("tower.app", "", "code"),
    ("postman.exe", "", "code"),
    ("postman.app", "", "code"),
    ("postman", "", "code"),
    ("insomnia.exe", "", "code"),
    ("insomnia.app", "", "code"),
    ("httpie.exe", "", "code"),
    ("httpie.app", "", "code"),
    ("tableplus.exe", "", "code"),
    ("tableplus.app", "", "code"),
    ("dbeaver.exe", "", "code"),
    ("dbeaver.app", "", "code"),
    ("pgadmin4.exe", "", "code"),
    ("mongodb compass.exe", "", "code"),
    ("mongodb compass.app", "", "code"),
    ("redisinsight.exe", "", "code"),
    ("docker desktop.exe", "", "code"),
    ("docker.app", "", "code"),
    ("docker desktop.app", "", "code"),
    ("windowsterminal.exe", "", "code"),
    ("wt.exe", "", "code"),
    ("powershell.exe", "", "code"),
    ("pwsh.exe", "", "code"),
    ("cmd.exe", "", "code"),
    ("windows terminal.app", "", "code"),
    ("terminal.app", "", "code"),
    ("iterm2.app", "", "code"),
    ("iterm.app", "", "code"),
    ("warp.app", "", "code"),
    ("hyper.exe", "", "code"),
    ("hyper.app", "", "code"),
    ("alacritty.exe", "", "code"),
    ("alacritty.app", "", "code"),
    ("alacritty", "", "code"),
    ("kitty", "", "code"),
    ("wezterm.exe", "", "code"),
    ("wezterm.app", "", "code"),
    ("wezterm", "", "code"),
    ("gnome-terminal", "", "code"),
    ("konsole", "", "code"),
    ("xfce4-terminal", "", "code"),
    ("tilix", "", "code"),
    ("terminator", "", "code"),
    ("putty.exe", "", "code"),
    ("mobaxterm.exe", "", "code"),
    ("winscp.exe", "", "code"),
    ("filezilla.exe", "", "code"),
    ("filezilla.app", "", "code"),
    ("cyberduck.exe", "", "code"),
    ("cyberduck.app", "", "code"),
    ("vim", "", "code"),
    ("nvim", "", "code"),
    ("nvim-qt.exe", "", "code"),
    ("gvim.exe", "", "code"),
    ("emacs", "", "code"),
    ("emacs.exe", "", "code"),
    ("emacs.app", "", "code"),
    ("helix", "", "code"),
    ("lazygit", "", "code"),
    // —— Design / creative ——
    ("figma.exe", "", "default"),
    ("figma.app", "", "default"),
    ("figma", "", "default"),
    ("sketch.app", "", "default"),
    ("adobe photoshop.exe", "", "default"),
    ("photoshop.exe", "", "default"),
    ("adobe photoshop 2024.exe", "", "default"),
    ("adobe photoshop 2025.exe", "", "default"),
    ("photoshop.app", "", "default"),
    ("adobe illustrator.exe", "", "default"),
    ("illustrator.exe", "", "default"),
    ("illustrator.app", "", "default"),
    ("adobe premiere pro.exe", "", "default"),
    ("premiere pro.exe", "", "default"),
    ("adobe premiere pro.app", "", "default"),
    ("afterfx.exe", "", "default"),
    ("adobe after effects.app", "", "default"),
    ("acrobat.exe", "", "formal"),
    ("acrobat reader.exe", "", "formal"),
    ("adobe acrobat.app", "", "formal"),
    ("acrobat reader.app", "", "formal"),
    ("preview.app", "", "default"),
    ("canva.exe", "", "default"),
    ("canva.app", "", "default"),
    ("affinity designer.exe", "", "default"),
    ("affinity designer 2.app", "", "default"),
    ("affinity photo.exe", "", "default"),
    ("affinity photo 2.app", "", "default"),
    ("affinity publisher.exe", "", "prose"),
    ("gimp.exe", "", "default"),
    ("gimp.app", "", "default"),
    ("gimp", "", "default"),
    ("inkscape.exe", "", "default"),
    ("inkscape.app", "", "default"),
    ("inkscape", "", "default"),
    ("krita.exe", "", "default"),
    ("krita.app", "", "default"),
    ("krita", "", "default"),
    ("miro.exe", "", "casual"),
    ("miro.app", "", "casual"),
    ("rize.exe", "", "default"),
    // —— Productivity / PM ——
    ("asana.exe", "", "formal"),
    ("asana.app", "", "formal"),
    ("trello.exe", "", "casual"),
    ("trello.app", "", "casual"),
    ("clickup.exe", "", "formal"),
    ("clickup.app", "", "formal"),
    ("todoist.exe", "", "casual"),
    ("todoist.app", "", "casual"),
    ("ticktick.exe", "", "casual"),
    ("ticktick.app", "", "casual"),
    ("things3.app", "", "casual"),
    ("things.app", "", "casual"),
    ("omnifocus.app", "", "formal"),
    ("anydo.exe", "", "casual"),
    ("calendly.exe", "", "formal"),
    ("fantastical.app", "", "formal"),
    ("calendar.app", "", "formal"),
    ("microsoft to do.exe", "", "casual"),
    ("microsoft to do.app", "", "casual"),
    ("reminders.app", "", "casual"),
    ("linear.exe", "", "formal"),
    ("linear.app", "", "formal"),
    ("height.exe", "", "formal"),
    ("notion calendar.app", "", "formal"),
    ("cron.app", "", "formal"),
    // —— CRM / business desktop ——
    ("salesforce.exe", "", "formal"),
    ("hubspot.exe", "", "formal"),
    ("zendesk.exe", "", "formal"),
    ("intercom.exe", "", "formal"),
    ("quickbooks.exe", "", "formal"),
    ("quickbooks.app", "", "formal"),
    ("xero.exe", "", "formal"),
    ("sage.exe", "", "formal"),
    ("freshbooks.exe", "", "formal"),
    ("wave.exe", "", "formal"),
    // —— Browsers (default when no title rule matches) ——
    ("chrome.exe", "", "default"),
    ("msedge.exe", "", "default"),
    ("firefox.exe", "", "default"),
    ("brave.exe", "", "default"),
    ("opera.exe", "", "default"),
    ("vivaldi.exe", "", "default"),
    ("arc.exe", "", "default"),
    ("chromium.exe", "", "default"),
    ("google chrome.app", "", "default"),
    ("microsoft edge.app", "", "default"),
    ("firefox.app", "", "default"),
    ("brave browser.app", "", "default"),
    ("safari.app", "", "default"),
    ("opera.app", "", "default"),
    ("arc.app", "", "default"),
    ("google-chrome", "", "default"),
    ("chromium", "", "default"),
    ("microsoft-edge", "", "default"),
    ("brave-browser", "", "default"),
    ("firefox", "", "default"),
    ("opera", "", "default"),
    // —— System / files ——
    ("explorer.exe", "", "default"),
    ("finder.app", "", "default"),
    ("nautilus", "", "default"),
    ("dolphin", "", "default"),
    ("thunar", "", "default"),
    ("pcmanfm", "", "default"),
    ("nemo", "", "default"),
    ("searchapp.exe", "", "default"),
    ("searchhost.exe", "", "default"),
    ("applicationframehost.exe", "", "default"),
    ("systemsettings.exe", "", "default"),
    ("system preferences.app", "", "default"),
    ("system settings.app", "", "default"),
    ("control.exe", "", "default"),
    // —— Misc apps people dictate into ——
    ("obs64.exe", "", "casual"),
    ("obs.exe", "", "casual"),
    ("obs.app", "", "casual"),
    ("streamlabs obs.exe", "", "casual"),
    ("audacity.exe", "", "default"),
    ("audacity.app", "", "default"),
    ("vlc.exe", "", "casual"),
    ("vlc.app", "", "casual"),
    ("vlc", "", "casual"),
    ("itunes.exe", "", "casual"),
    ("music.app", "", "casual"),
    ("podcasts.app", "", "casual"),
    ("kindle.exe", "", "prose"),
    ("kindle.app", "", "prose"),
    ("calibre.exe", "", "prose"),
    ("calibre.app", "", "prose"),
    ("zotero.exe", "", "prose"),
    ("zotero.app", "", "prose"),
    ("mendeley.exe", "", "prose"),
    ("mendeley.app", "", "prose"),
    ("grammarly.exe", "", "prose"),
    ("grammarly.app", "", "prose"),
    ("1password.exe", "", "formal"),
    ("1password.app", "", "formal"),
    ("1password", "", "formal"),
    ("bitwarden.exe", "", "formal"),
    ("bitwarden.app", "", "formal"),
    ("lastpass.exe", "", "formal"),
    ("keepassxc.exe", "", "formal"),
    ("keepassxc.app", "", "formal"),
    ("keepassxc", "", "formal"),
    ("notion calendar.exe", "", "formal"),
    ("raycast.app", "", "default"),
    ("alfred.app", "", "default"),
    ("spotlight", "", "default"),
];

/// Build the full seed list (native apps + browser×web-title matrix).
pub fn all_default_profiles() -> Vec<ProfileSeed> {
    let mut out: Vec<ProfileSeed> = Vec::with_capacity(450);
    out.extend_from_slice(NATIVE);
    for &browser in BROWSERS {
        for &(title, tone) in WEB_TONES {
            out.push((browser, title, tone));
        }
    }
    // Deduplicate exact (exe, title) pairs while preserving first tone.
    let mut seen = std::collections::HashSet::<(&str, &str)>::new();
    out.retain(|(exe, title, _)| seen.insert((*exe, *title)));
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn has_hundreds_of_presets() {
        let n = all_default_profiles().len();
        eprintln!("preset_count={n}");
        assert!(n >= 350, "expected >= 350 presets, got {n}");
    }

    #[test]
    fn gmail_and_discord_exist() {
        let all = all_default_profiles();
        assert!(all.iter().any(|(e, t, tone)| {
            *e == "chrome.exe" && *t == "Gmail" && *tone == "formal"
        }));
        assert!(all
            .iter()
            .any(|(e, t, tone)| { *e == "discord.exe" && t.is_empty() && *tone == "casual" }));
    }
}
