-keepattributes Signature
-keepattributes *Annotation*
-keep class com.maxspeech.android.** { *; }
-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn org.conscrypt.**
-keep class androidx.datastore.** { *; }
